// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SpotifyOpgaveCore.Models;
using System;

namespace SpotifyOpgaveCore.Migrations
{
    [DbContext(typeof(RoomContext))]
    [Migration("20181213121449_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpotifyOpgaveCore.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Owner");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SpotifyOpgaveCore.Models.Song", b =>
                {
                    b.Property<string>("SongID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Duration");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<int?>("RoomId");

                    b.HasKey("SongID");

                    b.HasIndex("RoomId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SpotifyOpgaveCore.Models.Song", b =>
                {
                    b.HasOne("SpotifyOpgaveCore.Models.Room")
                        .WithMany("Songs")
                        .HasForeignKey("RoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
